### ISSUE TITLE
ディレクトリ構成の変更

### ISSUE THREAD

**Issue by zer0-star** [zer0-star/Nim-ACL#16]
いまのところ検討しているもの

- `src/nim_acl.nim` を削除して、`src/nim_acl/` を `atcoder/` にする
  - これをすると、nimble で管理できなくなる
    - 現状手元でも `src/nim_acl/modint` と書かないといけないなら、同じかも
- package 名を `atcoder` にして、`src/nim_acl/` を `src/atcoder/` にする
  - import のときは `atcoder/modint` で OK
  - expander.py では `atcoder/` で始まるパスに対応すればいい
  - verify のときは事前に `mv src/atcoder ./` とする

後者の方が圧倒的によさそう

**Comment by chaemon** [comment]
あーnimbleで管理できなくなるのですねー名前なんでもいいのかと思ったんですがそうでもないのですねー

後者がいいと思いますね♪

**Comment by chaemon** [comment]
それから、ディレクトリ構成といえば、src/nim_acl配下に全部あるのってわかりにくいから、graph, math, string, data_structure...みたいにカテゴリ分けしませんか！？

**Comment by zer0-star** [comment]
カテゴリわけもしようと思ったんですが、それだと本家の ACL と使い方が変わってしまうのが難しいところなんですよね......

ただ他のファイルを include するだけのファイルを作るというのもできなくはないですが......
