### ISSUE TITLE
definedじゃだめっぽい

### ISSUE THREAD

**Issue by chaemon** [zer0-star/Nim-ACL#18]
そういえば、気づいたんですが、インクルードガードするとき、

```
when not defined HOGE_HPP:
  const HOGE_HPP = 1
when not defined HOGE_HPP:
  const HOGE_HPP = 1
```

だと、二番目でredefinition errorになるようです。つまり、一回目のconstで定義してもそれが検知されていないです。definedはコンパイルオプションか何かで指定されたものがあるかみたいなコマンドで正しくはdeclaredにしないといけないっぽいです。

**Comment by chaemon** [comment]
と、思ったけど、ちょっと自信がなくてdeclaredでよいかもわからないので、確認をお願いします！

**Comment by zer0-star** [comment]
あー、これ `declared` じゃなきゃだめですね......忘れていました

**Comment by zer0-star** [comment]
`declared` だと大丈夫だと思います

**Comment by chaemon** [comment]
では、全部declaredにしときますね！
