### ISSUE TITLE
math.nimというファイルがあるとimport mathを実行したときに不具合が起こる

### ISSUE THREAD

**Issue by chaemon** [zer0-star/Nim-ACL#19]
標記の通り、ACLにmath.nimというファイルがあると、Nimの標準ライブラリのmathが読めないようですがどうしますかね。

**Comment by zer0-star** [comment]
将来的に、verification-helper や expander.py との兼ね合いもあって、config.nims を置くことで `import atcoder/math` で読み込めるようにしたいと考えています。そうすれば、この問題も解決すると思います。ただ、そうなるのはディレクトリ構成の変更の後になると思います。

**Comment by chaemon** [comment]
import std/math.nimで大丈夫らしいので、この標記に統一してクローズします。
