### ISSUE TITLE
[verify] extra/math/pow_of_formal_power_series_test.nimのverifyが失敗する

### ISSUE THREAD

**Issue by haruyama480** [zer0-star/Nim-ACL#52]
```
% ulimit -s 65000  
% oj-verify run verify/extra/math/pow_of_formal_power_series_test.nim
(略)
[INFO] slowest: 0.780420 sec  (for M_zero_00)
[FAILURE] test failed: 4 AC / 32 cases
(略)
```

結構失敗しちゃいます
これは手強そう

**Comment by chaemon** [comment]
https://atcoder.jp/contests/abc317/submissions/46642639

一応、1.6.14で利用実績はあってACしているんですが、環境依存なんですかね。。。

**Comment by haruyama480** [comment]
AC実績情報ありがたいです

**Comment by haruyama480** [comment]
overflowしてる..?
```
[INFO] monomial_02
fatal.nim(54)            sysFatal
Error: unhandled exception: over- or underflow [OverflowDefect]
```

**Comment by chaemon** [comment]
それは重要な手がかりですね！

**Comment by chaemon** [comment]
単純な入力でも落ちてるようです。

[FAILURE] WA
input:
2_0
0_0

output:
0_0

expected:
1_0

**Comment by chaemon** [comment]
あと、こちらの環境では4個ではなく18個は通りましたよ！

[FAILURE] test failed: 18 AC / 32 cases

**Comment by chaemon** [comment]
Nim-ACL/src/atcoder/extra/math/formal_power_series.nim(485)でunderflowが起こっているようです。

/Users/toshihiroshimizu/git/Nim-ACL/src/verify/extra/math/pow_of_formal_power_series_test.nim(15) pow_of_formal_power_series_test
/Users/toshihiroshimizu/git/Nim-ACL/src/verify/extra/math/pow_of_formal_power_series_test.nim(13) main
/Users/toshihiroshimizu/git/Nim-ACL/src/atcoder/extra/math/formal_power_series.nim(485) pow
/Users/toshihiroshimizu/.choosenim/toolchains/nim-1.6.14/lib/system/fatal.nim(54) sysFatal
Error: unhandled exception: over- or underflow [OverflowDefect]

**Comment by chaemon** [comment]
あ、わかりました！485行目のif i * k > deg:というところのi * kでオーバーフローしているようです。

**Comment by haruyama480** [comment]
ちょうど自分もそこ見てました!
FPSちゃんと学習できてないので、一旦調査任せてもいいですか?

**Comment by chaemon** [comment]
はい。degは配列の長さ分しかとらないので常識的な大きさであれば、if i > deg or k > deg or i * k > deg:とすれば良さそうです。

**Comment by chaemon** [comment]
さっきの0^0のケース以外AC出せました！

[INFO] slowest: 1.451678 sec  (for M_zero_00)
[INFO] max memory: 67.224000 MB  (for monomial_01)
[FAILURE] test failed: 31 AC / 32 cases

**Comment by chaemon** [comment]
0乗の場合に無条件で1にするようにしたら全部ACしました。

PRとか面倒なので、直接pushしちゃいました。すみません。。。

**Comment by chaemon** [comment]
変更点はこちらです。

https://github.com/zer0-star/Nim-ACL/commit/80bbcdea1738f47955707cd24547d584607b8dfb

**Comment by haruyama480** [comment]
ありがとうございます！

> degは配列の長さ分しかとらないので常識的な大きさであれば、if i > deg or k > deg or i * k > deg:とすれば良さそう

まさにこれですね

これでfloatの件以外はverifyできましたね:tada:
closeよろしくお願いします

**Comment by chaemon** [comment]
上記の利用実績ではべき乗するkの値が小さくてi*kでオーバーフローしないのでちゃんと動作していたんですかねー
